spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    livereload:
      enabled: true
logging:
  config: classpath:logback.xml
#jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor